---
name: Checks

on: [push]

jobs:
  test-list:
    name: Test
    # ubuntu already has docker-compose installed as predetermined
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DUCKERHUB_TOKEN }}
      - name: Checkout
        run: docker compose run --rm app sh -c "python manage.py test"
